name: http-types

# Trigger the workflow on pull requests or a push (but only for the 'master' branch)
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.hs"
      - "**.cabal"
      - "stack.yaml"
      - ".github/workflows/ci.yml"
  push:
    branches: [master]

jobs:
  cabal:
    env:
      MANUAL_RESET: v4
    name: cabal / ghc-${{matrix.ghc}} / ${{ matrix.os }}
    continue-on-error: ${{ matrix.ghc == '9.14.1'}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest # Is giving issues for some reason
        cabal: ["latest"]
        ghc:
          - "9.6.7"
          - "9.8.4"
          - "9.10.3"
          - "9.12.4"
          - "9.14.1"

    steps:
      - uses: actions/checkout@v4

      - name: Cache GHCup
        uses: actions/cache@v6
        id: ghcup-cache
        with:
          path: |
            ~/.ghcup/bin/*
            ~/.ghcup/cache/*
            ~/.ghcup/config.yaml
            ~/.ghcup/ghc/${{ matrix.ghc }}
          key: CI-ghcup-cabal-${{ env.MANUAL_RESET }}-${{ matrix.ghc }}

      - name: Setup Haskell
        if: steps.ghcup-cache.outputs.cache-hit != 'true'
        uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          cabal-update: true

      - name: Cache cabal
        uses: actions/cache@v6
        with:
          path: ~/.cabal
          key: ${{ matrix.ghc }}-cabal

      - name: Build
        run: |
          cabal build all --enable-tests --enable-benchmarks --write-ghc-environment-files=always --ghc-option='-Wall'
      - name: Test
        run: |
          cabal test test:spec --enable-tests --ghc-option='-Wall'
      - name: Test Docs
        run: |
          cabal exec -- cabal test test:doctests --enable-tests --ghc-option='-Wall'
    # # We probably want to add benchmarks at some point, just to make sure
    # # functions don't regress in performance too much?
    # - name: Bench
    #   run: |
    #     cabal bench --enable-benchmarks
  stack:
    name: stack ${{ matrix.resolver }}
    env:
      MANUAL_RESET: v3
    runs-on: ubuntu-latest
    # This makes the CI jobs not all be cancelled if nightly fails to build.
    # However, if nightly fails to build, CI still gets a red X in the GitHub UI.
    # Ideally we want CI as a whole to pass even if nightly fails.
    # There doesn't appear to be a way to work around this for now.
    #
    # When some sort of `allow-failure` functionality is available in GitHub
    # actions, we should switch to it:
    # https://github.com/actions/toolkit/issues/399
    continue-on-error: ${{ matrix.resolver == 'nightly' || matrix.resolver == 'lts-12' }}
    strategy:
      matrix:
        include:
          - resolver: "lts-12"
            ghc: "8.4.4"
          - resolver: "lts-22"
            ghc: "9.6.7"
          - resolver: "lts-23"
            ghc: "9.8.4"
          - resolver: "lts-24"
            ghc: "9.10.3"
          - resolver: "nightly"
            ghc: "9.12.4"

    steps:
      - uses: actions/checkout@v4

      - name: Cache GHCup
        uses: actions/cache@v6
        id: ghcup-cache
        with:
          path: |
            ~/.ghcup/bin/*
            ~/.ghcup/cache/*
            ~/.ghcup/config.yaml
            ~/.ghcup/ghc/${{ matrix.ghc }}
            ~/.ghcup/stack/*
          key: CI-ghcup-stack-${{ env.MANUAL_RESET }}-${{ matrix.ghc }}

      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        if: steps.ghcup-cache.outputs.cache-hit != 'true'
        with:
          stack-version: "latest"
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-setup-ghc: false

      - name: Cache Pantry (Stackage package index)
        id: pantry
        uses: actions/cache@v6
        with:
          path: ~/.stack/pantry
          key: CI-pantry-${{ env.MANUAL_RESET }}-${{ matrix.resolver }}

      - name: Recompute Stackage package index
        if: steps.pantry.outputs.cache-hit != 'true'
        run: stack update # populates ~/.stack/pantry

      - name: Cache Dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.stack/stack.sqlite3
            ~/.stack/snapshots
          key: ${{ runner.os }}-${{ matrix.resolver }}-stack

      - name: Build lts-12
        if: "${{ matrix.resolver == 'lts-12' }}"
        run: |
          stack config set system-ghc true --global
          stack build --resolver=${{ matrix.resolver }} --ghc-options='-Wall'

      - name: Build
        if: "${{ matrix.resolver != 'lts-12' }}"
        run: |
          stack config set system-ghc true --global
          stack build --resolver=${{ matrix.resolver }} --test --bench \
            --no-run-tests --no-run-benchmarks --ghc-options='-Wall'
      - name: Test
        if: "${{ matrix.resolver != 'lts-12' }}"
        run: |
          stack test --no-rerun-tests http-types:test:spec --resolver=${{ matrix.resolver }}
      - name: Test Docs
        if: "${{ matrix.resolver != 'lts-12' }}"
        run: |
          stack test http-types:test:doctests --resolver=${{ matrix.resolver }}

    # # We probably want to add benchmarks at some point, just to make sure
    # # functions don't regress in performance too much?
    # - name: Bench
    #   run: |
    #     stack bench ${{ matrix.resolver }}
